### ISSUE TITLE
Support for Python 3.x

### ISSUE THREAD

**Issue by JohnOmernik** [mkmoisen/pychbase#118]
Hey, great work here, I would love to see support for Python 3.x. When I tried to pip install I got an issue related to the use of print statements (need parens). 

Collecting pychbase
  Downloading pychbase-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oytiuu_z/pychbase/setup.py", line 123
        print ex
               ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by mkmoisen** [comment]
@JohnOmernik This is my first C extension and I only know how to do that in Python 2. I won't be able to add Python 3 support for some time. Sorry!
