### ISSUE TITLE
Error importing pychbase - undefined symbol: JNI_GetCreatedJavaVMs

### ISSUE THREAD

**Issue by JohnOmernik** [mkmoisen/pychbase#120]
I've updated my ENV variables to point to the right dirs, (see $env) and the path is correct and lbjvm.so exists... but still getting the traceback when I try to import... not sure what is happening here... it maybe related to #119 where I added -fpermissive to get things building...

$env

LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:/opt/mapr/lib
PYCHBASE_LIBJVM_DIR=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

The path is correct:

ls -ls /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
total 33036
    4 -rw-r--r-- 16 root root     1423 Jan 23 15:58 Xusage.txt
19620 -r--r--r-- 16 root root 20090880 Apr  5 21:17 classes.jsa
    0 lrwxrwxrwx  1 root root       13 Jan 23 17:05 libjsig.so -> ../libjsig.so
13412 -rw-r--r-- 16 root root 13730408 Jan 23 17:05 libjvm.so

Trace:

>>> from pychbase import Connection, Table, Batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pychbase/__init__.py", line 1, in <module>
    from pychbase._pychbase import _connection, _table, HBaseError
ImportError: /opt/mapr/lib/libMapRClient.so: undefined symbol: JNI_GetCreatedJavaVMs

**Comment by JohnOmernik** [comment]
I am not sure why this worked, but specifying LD_PRELOAD=/path/to/libjvm.so  fixes the issue and all works... tenacious hacking around, not really an understood solution.

**Comment by mkmoisen** [comment]
@JohnOmernik 

Were you able to get everything installed and working OK using this workaround? Have you tried the tests?

**Comment by mkmoisen** [comment]
@JohnOmernik 

Would you let me know what version of linux you are using, your C compiler and version, your MapR version, your Python version, and the exact steps you took to get it to work? I would like to include the information in the README and try to find the root cause. Thanks!
